import type { Agent, Copier } from '../types/agent';

export const mockAgents: Agent[] = [
  {
    id: 'agent-1',
    hostname: 'PC-KETOAN-01',
    ipAddress: '192.168.1.101',
    os: 'Windows 10 Pro',
    status: 'online',
    lastSeen: new Date().toISOString(),
    printerConfig: { brand: 'Ricoh', model: 'MP 7503', driverName: 'Ricoh MP 7503 PCL6', printerIp: '192.168.1.200', port: 9100 },
    scanConfig: {
      enableSmb: true, enableFtp: false, priority: 'smb', autoConfig: true,
      smb: { server: '192.168.1.10', path: '/scan/ketoan', username: 'scanner', password: 'scan123' },
    },
    driverInstalled: true, scanSmbInstalled: true, scanFtpInstalled: false, scanConfigured: true,
  },
  {
    id: 'agent-2',
    hostname: 'PC-KINHDOANH-02',
    ipAddress: '192.168.1.102',
    os: 'Windows 11 Pro',
    status: 'online',
    lastSeen: new Date().toISOString(),
    driverInstalled: false, scanSmbInstalled: false, scanFtpInstalled: false, scanConfigured: false,
  },
  {
    id: 'agent-3',
    hostname: 'PC-NHANSU-03',
    ipAddress: '192.168.1.103',
    os: 'Windows 10 Pro',
    status: 'online',
    lastSeen: new Date().toISOString(),
    printerConfig: { brand: 'Toshiba', model: 'e-STUDIO 556', driverName: 'Toshiba e-STUDIO 556 PS', printerIp: '192.168.1.201', port: 9100 },
    scanConfig: {
      enableSmb: true, enableFtp: true, priority: 'ftp', autoConfig: true,
      smb: { server: '192.168.1.10', path: '/scan/nhansu', username: 'scanner', password: 'scan123' },
      ftp: { server: '192.168.1.10', path: '/ftp/nhansu', username: 'ftpuser', password: 'ftp456' },
    },
    driverInstalled: true, scanSmbInstalled: true, scanFtpInstalled: true, scanConfigured: true,
  },
  {
    id: 'agent-4',
    hostname: 'PC-GIAMSAT-04',
    ipAddress: '192.168.1.104',
    os: 'Windows 10 LTSC',
    status: 'offline',
    lastSeen: '2026-02-18T15:30:00.000Z',
    driverInstalled: false, scanSmbInstalled: false, scanFtpInstalled: false, scanConfigured: false,
  },
  {
    id: 'agent-5',
    hostname: 'PC-PHONGBAN-05',
    ipAddress: '192.168.1.105',
    os: 'Windows 11 Pro',
    status: 'online',
    lastSeen: new Date().toISOString(),
    printerConfig: { brand: 'Ricoh', model: 'MP 2014', driverName: 'Ricoh MP 2014 PCL6', printerIp: '192.168.1.202', port: 9100 },
    scanConfig: {
      enableSmb: false, enableFtp: true, priority: 'ftp', autoConfig: false,
      ftp: { server: '192.168.1.10', path: '/scan/phongban', username: 'ftpuser', password: 'ftp456' },
    },
    driverInstalled: true, scanSmbInstalled: false, scanFtpInstalled: true, scanConfigured: false,
  },
  {
    id: 'agent-6',
    hostname: 'PC-KYTHUAT-06',
    ipAddress: '192.168.1.106',
    os: 'Windows 10 Pro',
    status: 'online',
    lastSeen: new Date().toISOString(),
    printerConfig: { brand: 'Xerox', model: 'WorkCentre 7855', driverName: 'Xerox WorkCentre 7855 PS', printerIp: '192.168.1.203', port: 9100 },
    driverInstalled: true, scanSmbInstalled: false, scanFtpInstalled: false, scanConfigured: false,
  },
];

export const mockCopiers: Copier[] = [
  {
    id: 'AA:BB:CC:11:22:33',
    macId: 'AA:BB:CC:11:22:33',
    name: 'Ricoh MP 7503 - Tầng 2',
    brand: 'Ricoh',
    model: 'MP 7503',
    ipAddress: '192.168.1.200',
    status: 'online',
    lastSeen: new Date().toISOString(),
    connectedPCs: ['PC-KETOAN-01', 'PC-KINHDOANH-02'],
    driverVersion: 'PCL6 v4.18',
    location: 'Phòng kế toán - Tầng 2',
    webUsername: 'admin',
    webPassword: 'ricoh@123',
    isConfigured: true,
  },
  {
    id: 'AA:BB:CC:44:55:66',
    macId: 'AA:BB:CC:44:55:66',
    name: 'Toshiba e-STUDIO 556 - Tầng 3',
    brand: 'Toshiba',
    model: 'e-STUDIO 556',
    ipAddress: '192.168.1.201',
    status: 'online',
    lastSeen: new Date().toISOString(),
    connectedPCs: ['PC-NHANSU-03'],
    driverVersion: 'PS v3.2',
    location: 'Phòng nhân sự - Tầng 3',
    webUsername: 'admin',
    webPassword: '',
    isConfigured: true,
  },
  {
    id: 'AA:BB:CC:77:88:99',
    macId: 'AA:BB:CC:77:88:99',
    name: 'Ricoh MP 2014 - Tầng 1',
    brand: 'Ricoh',
    model: 'MP 2014',
    ipAddress: '192.168.1.202',
    status: 'online',
    lastSeen: new Date().toISOString(),
    connectedPCs: ['PC-PHONGBAN-05'],
    driverVersion: 'PCL6 v4.10',
    location: 'Phòng ban - Tầng 1',
    isConfigured: false,
  },
  {
    id: 'DD:EE:FF:11:22:33',
    macId: 'DD:EE:FF:11:22:33',
    name: 'Xerox WorkCentre 7855 - Tầng 4',
    brand: 'Xerox',
    model: 'WorkCentre 7855',
    ipAddress: '192.168.1.203',
    status: 'offline',
    lastSeen: '2026-02-19T08:00:00.000Z',
    connectedPCs: ['PC-KYTHUAT-06'],
    driverVersion: 'PS v5.1',
    location: 'Phòng kỹ thuật - Tầng 4',
    isConfigured: false,
  },
];
