hiddenimports = [
    '_sqlite3',
    'flask',
    'requests',
    'sqlite3',
    'ctypes',
    'pyftpdlib',
    'pyftpdlib.authorizers',
    'pyftpdlib.handlers',
    'pyftpdlib.servers',
    'xml.etree.ElementTree',
    'xml.etree',
    'ipaddress',
    'ftplib',
    'zipfile',
    'winreg',
    'csv',
    'platform',
    'urllib.request',
    'urllib.parse',
    'uuid',
    'unicodedata'
]

a = Analysis(
    ['agent_loader.py'],
    pathex=['.'],
    binaries=[],
    datas=[('agent_core.zip', '.')],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['agent', 'torch', 'torchvision', 'torchaudio', 'sklearn', 'scipy', 'matplotlib', 'numba', 'llvmlite', 'pandas', 'cv2', 'PIL', 'imageio_ffmpeg', 'IPython', 'jupyter', 'notebook', 'traitlets'],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='printagent',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['agent\\icon.ico'],
)
