from __future__ import annotations

import logging
import re
import threading
import time
from dataclasses import dataclass
from html import unescape
from pathlib import Path
from typing import Any
from urllib.parse import urljoin

import requests

from agent.services.api_client import APIClient, Printer

LOGGER = logging.getLogger(__name__)
ADDRESS_DEBUG_LOG_FILE = Path("storage/data/address_list_debug.log")

@dataclass
class AddressEntry:
    type: str
    registration_no: str
    name: str
    user_code: str
    date_last_used: str
    email_address: str
    folder: str
    entry_id: str = ""

class RicohServiceBase:
    def __init__(self, api_client: APIClient, interval_seconds: int = 60) -> None:
        self.api_client = api_client
        self.interval_seconds = interval_seconds
        self._stop_event = threading.Event()
        self._thread: threading.Thread | None = None
        # Keep a monotonic local hint so address registration_no generated by app always increases.
        self._address_index_hint_by_ip: dict[str, int] = {}

    def _timestamp(self) -> str:
        return time.strftime("%Y-%m-%d %H:%M:%S")

    def _append_address_debug(self, message: str) -> None:
        try:
            ADDRESS_DEBUG_LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
            with ADDRESS_DEBUG_LOG_FILE.open("a", encoding="utf-8") as f:
                f.write(f"{self._timestamp()} {message}\n")
        except Exception as exc:  # noqa: BLE001
            LOGGER.warning("Failed to write address debug log: %s", exc)

    @staticmethod
    def _http_get(url: str, timeout: int = 10, session: requests.Session | None = None) -> str:
        if session:
            resp = session.get(url, timeout=timeout)
        else:
            resp = requests.get(url, timeout=timeout)
        resp.raise_for_status()
        return resp.text

    def _logout_after_collect(self, printer: Printer, source: str = "") -> None:
        logout_url = f"http://{printer.ip}/web/entry/en/websys/webArch/logout.cgi"
        try:
            # We don't bother checking response, typically we just hit it and move on.
            requests.get(logout_url, timeout=5)
            LOGGER.info("Logged out from %s (%s)", printer.name, source)
        except Exception as exc:  # noqa: BLE001
            LOGGER.debug("Logout failed (expected for some models): ip=%s error=%s", printer.ip, exc)

    def _verify_session_state(self, session: requests.Session, printer: Printer, username: str) -> bool:
        """
        Loads a protected page to confirm whether we are fully logged in
        with a valid administrative session.
        """
        test_paths = [
            "/web/entry/en/address/adrsList.cgi?modeIn=LIST_ALL",
            "/web/guest/en/address/adrsList.cgi?modeIn=LIST_ALL"
        ]
        for test_path in test_paths:
            test_url = urljoin(f"http://{printer.ip}", test_path)
            try:
                test_resp = session.get(test_url, timeout=10)
                is_login_page = any(indicator in test_resp.text for indicator in ["authForm.cgi", "login.cgi", "Login User Name"])
                if test_resp.status_code == 200 and not is_login_page:
                    return True
            except Exception:
                continue
        return False

    def _login(self, session: requests.Session, printer: Printer, credential_candidates: list[tuple[str, str]] | None = None) -> tuple[str, str]:
        """
        Unified login logic that tries multiple credential pairs.
        Cycles through candidates: (user, password).
        Returns successfully used (user, password) tuple.
        """
        base_url = f"http://{printer.ip}"
        LOGGER.info("[RicohLogin] Starting login process for copier %s (IP: %s)", printer.name, printer.ip)
        
        # 1. First, always reset/logout to ensure we aren't in a broken state.
        try:
            LOGGER.info("[RicohLogin] Clearing session cookies...")
            session.cookies.clear()
        except Exception as exc:
            LOGGER.debug("[RicohLogin] Cookies clear failed (non-critical): %s", exc)
        
        LOGGER.info("[RicohLogin] Resetting pre-existing web session on copier...")
        self._reset_web_session(session, printer)
        
        # 2. Build candidate list.
        candidates = []
        if credential_candidates:
            candidates.extend(credential_candidates)
        
        if printer.user or printer.password:
            candidates.append((printer.user or "", printer.password or ""))
        
        candidates.extend([
            ("admin", ""),
            ("admin", "admin"),
        ])
        
        # Deduplicate candidates while preserving order.
        seen = set()
        final_candidates = []
        for u, p in candidates:
            if (u, p) not in seen:
                seen.add((u, p))
                final_candidates.append((u, p))
 
        LOGGER.info("[RicohLogin] Dedicated list of credentials to attempt: %s", [(u, "***" if p else "") for u, p in final_candidates])
 
        last_exception = None
        for attempt, (user, password) in enumerate(final_candidates):
            LOGGER.info("[RicohLogin] Attempt %d/%d: user=%s, password=%s", attempt + 1, len(final_candidates), user, "***" if password else "<empty>")
            
            # Reset session for this specific candidate to prevent cookie contamination
            try:
                session.cookies.clear()
            except Exception:
                pass
                
            try:
                # A. Dynamic token extraction before POST login (like in the standalone script)
                get_urls = [
                    "/web/entry/en/websys/webArch/authForm.cgi",
                    "/web/guest/en/websys/webArch/authForm.cgi",
                ]
                
                wim_token = ""
                fetched_url = ""
                hidden_inputs = {}
                
                for get_path in get_urls:
                    url = urljoin(base_url, get_path)
                    # Try up to 2 times to handle cookieOnOffChecker setting/refresh logic
                    for pass_num in (1, 2):
                        try:
                            LOGGER.info("[RicohLogin] Fetching login form to extract wimToken: GET %s (pass %d)...", get_path, pass_num)
                            get_resp = session.get(url, timeout=15)
                            if get_resp.status_code == 200:
                                fetched_url = get_resp.url
                                hidden_inputs = self._extract_hidden_inputs(get_resp.text)
                                wim_token = hidden_inputs.get("wimToken", "")
                                
                                # Fallback direct regex check if not found in hidden inputs
                                if not wim_token:
                                    match = re.search(r'wimToken\s*=\s*["\']([^"\']+)["\']', get_resp.text)
                                    if match:
                                        wim_token = match.group(1)
                                    else:
                                        match2 = re.search(r'wimToken["\']\s*[^>]*value=["\']([^"\']+)["\']', get_resp.text, re.IGNORECASE)
                                        if not match2:
                                            match2 = re.search(r'value=["\']([^"\']+)["\']\s*[^>]*wimToken', get_resp.text, re.IGNORECASE)
                                        if match2:
                                            wim_token = match2.group(1)
                                
                                if wim_token:
                                    LOGGER.info("[RicohLogin] wimToken DETECTED: %s", wim_token)
                                    break
                                else:
                                    LOGGER.info("[RicohLogin] wimToken NOT DETECTED (pass %d, cookies: %s)", pass_num, session.cookies.get_dict())
                        except Exception as e:
                            LOGGER.debug("[RicohLogin] Failed to fetch GET page %s (pass %d): %s", get_path, pass_num, e)
                    if wim_token:
                        break
                
                # B. Perform authenticating POST requests ONLY to entry endpoints (Method A)
                post_paths = [
                    "/web/entry/en/websys/webArch/login.cgi",
                    "/web/entry/en/websys/webArch/authForm.cgi",
                ]
                
                success = False
                for path in post_paths:
                    post_url = urljoin(base_url, path)
                    LOGGER.info("[RicohLogin] Sending standard credentials (Method A): POST %s...", path)
                    
                    data = {}
                    if hidden_inputs:
                        data.update(hidden_inputs)
                        
                    data.update({
                        "username": user,
                        "password": password,
                    })
                    if wim_token:
                        data["wimToken"] = wim_token
                    
                    headers = {}
                    if fetched_url:
                        headers["Referer"] = fetched_url
                        
                    try:
                        resp = session.post(
                            post_url,
                            data=data,
                            headers=headers,
                            timeout=15
                        )
                        
                        LOGGER.info("[RicohLogin] Cookies after login attempt: %s", session.cookies.get_dict())
                        
                        is_login_page = any(indicator in resp.text for indicator in ["Login User Name", "Login Password"])
                        is_still_login_form = 'name="username"' in resp.text or 'name=\'username\'' in resp.text
                        wim_session = session.cookies.get("wimsesid", "")
                        real_session = bool(wim_session) and wim_session != "--"
                        
                        if resp.status_code == 200 and not is_login_page and not is_still_login_form and real_session:
                            if self._verify_session_state(session, printer, user):
                                LOGGER.info("[RicohLogin] Success! Logged in as '%s' via Method A (%s)", user, path)
                                success = True
                                break
                            else:
                                LOGGER.warning("[RicohLogin] Method A login completed but protected page check failed.")
                        else:
                            LOGGER.info("[RicohLogin] Failed Method A POST %s: Status %d, Login page indicator=%s, Real Session=%s", 
                                        path, resp.status_code, is_login_page or is_still_login_form, real_session)
                    except Exception as req_exc:
                        LOGGER.warning("[RicohLogin] Request to Method A POST %s failed: %s", path, req_exc)
                        continue
                
                if success:
                    printer.user = user
                    printer.password = password
                    return (user, password)
                
                # C. Method B: Base64-encoded credentials (required for some models like MP 6503 with empty password)
                LOGGER.info("[RicohLogin] Method A standard login failed. Trying Base64 fallback (Method B) for user %s...", user)
                try:
                    import base64
                    auth_form_url = urljoin(base_url, "/web/guest/en/websys/webArch/authForm.cgi?open=websys/webArch/authForm.cgi")
                    auth_resp = session.get(auth_form_url, timeout=15)
                    if auth_resp.status_code == 200:
                        token = self._extract_wim_token(auth_resp.text)
                        action_match = re.search(r'<form[^>]+action=["\']([^"\']+)["\']', auth_resp.text, re.IGNORECASE)
                        action = action_match.group(1) if action_match else "login.cgi"
                        
                        encoded_user = base64.b64encode(user.encode()).decode()
                        encoded_pass = base64.b64encode(password.encode()).decode()
                        
                        login_post_url = urljoin(auth_resp.url, action)
                        payload = {
                            "userid": encoded_user,
                            "password": encoded_pass,
                            "wimToken": token,
                            "open": "websys/webArch/authForm.cgi"
                        }
                        
                        LOGGER.info("[RicohLogin] Sending base64 credentials (Method B) to %s...", login_post_url)
                        resp = session.post(login_post_url, data=payload, headers={"Referer": auth_resp.url}, timeout=15)
                        LOGGER.info("[RicohLogin] Cookies after base64 login attempt: %s", session.cookies.get_dict())
                        
                        is_login_page = any(indicator in resp.text for indicator in ["Login User Name", "Login Password"])
                        wim_session = session.cookies.get("wimsesid", "")
                        real_session = bool(wim_session) and wim_session != "--"
                        
                        if resp.status_code == 200 and not is_login_page and real_session:
                            if self._verify_session_state(session, printer, user):
                                LOGGER.info("[RicohLogin] Success! Logged in as '%s' via Method B", user)
                                printer.user = user
                                printer.password = password
                                return (user, password)
                            else:
                                LOGGER.warning("[RicohLogin] Method B login completed but protected page check failed.")
                        else:
                            LOGGER.info("[RicohLogin] Failed Method B: Status %d, Login page indicator=%s, Real Session=%s", 
                                        resp.status_code, is_login_page, real_session)
                except Exception as e:
                    LOGGER.error("[RicohLogin] Failed in Base64 fallback (Method B) for user %s: %s", user, e)
                
            except Exception as exc:
                LOGGER.exception("[RicohLogin] Exception during credential trial: %s", exc)
                last_exception = exc
                
            if attempt < len(final_candidates) - 1:
                LOGGER.info("[RicohLogin] Waiting 1 second before trying next credential candidate...")
                time.sleep(1)
                continue

        if last_exception:
            raise last_exception
        raise RuntimeError(f"All login attempts failed for {printer.ip}")

    def _login_auth_form_only(self, session: requests.Session, printer: Printer) -> None:
        """Deprecated/Legacy: Use unified _login instead if possible."""
        self._login(session, printer)

    def _reset_web_session(self, session: requests.Session, printer: Printer) -> None:
        base_url = f"http://{printer.ip}"
        # Best-effort logout/cleanup
        urls = [
            "/web/entry/en/websys/webArch/logout.cgi",
            "/web/guest/en/websys/webArch/logout.cgi",
            "/web/entry/en/websys/webArch/mainFrame.cgi",
            "/web/guest/en/websys/webArch/mainFrame.cgi",
        ]
        LOGGER.info("[RicohSessionReset] Cleaning up pre-existing sessions for %s. Sending 4 GET requests (timeout=10s each)...", printer.ip)
        for target in urls:
            url = urljoin(base_url, target)
            start_time = time.time()
            try:
                LOGGER.info("[RicohSessionReset] GET %s ...", target)
                resp = session.get(url, timeout=10)
                elapsed = time.time() - start_time
                LOGGER.info("[RicohSessionReset] GET %s -> Status %d (%.2fs)", target, resp.status_code, elapsed)
            except Exception as exc:  # noqa: BLE001
                elapsed = time.time() - start_time
                LOGGER.info("[RicohSessionReset] GET %s failed/timed out after %.2fs: %s", target, elapsed, exc)
                continue
        try:
            LOGGER.info("[RicohSessionReset] Clearing session cookies...")
            session.cookies.clear()
        except Exception as exc:  # noqa: BLE001
            LOGGER.debug("[RicohSessionReset] Clear cookies error: %s", exc)
            return

    def reset_web_session(self, printer: Printer) -> None:
        """
        Public helper used by UI/polling flow to force-clear web session cookies
        on device side without requiring authentication.
        """
        session = requests.Session()
        try:
            self._reset_web_session(session, printer)
        finally:
            try:
                session.close()
            except Exception:  # noqa: BLE001
                pass

    def create_http_client(self, printer: Printer, credential_candidates: list[tuple[str, str]] | None = None, authenticated: bool = True) -> requests.Session:
        """
        Creates a session. If authenticated=True, performs login.
        """
        LOGGER.info("[RicohClient] Creating requests session: IP=%s, authenticated=%s", printer.ip, authenticated)
        session = requests.Session()
        session.headers.update({"User-Agent": "printer-agent/0.1"})
        
        if authenticated:
            self._login(session, printer, credential_candidates=credential_candidates)
        return session

    def create_http_client_auth_form_only(self, printer: Printer) -> requests.Session:
        """Deprecated: Use create_http_client instead."""
        return self.create_http_client(printer, authenticated=True)

    def authenticate_and_get(self, session: requests.Session, printer: Printer, target_url: str) -> str:
        """
        Compatibility layer: Ensures we are logged in and fetches the target.
        """
        url = urljoin(f"http://{printer.ip}", target_url)
        LOGGER.info("[RicohHTTP] GET %s (timeout=15s)", target_url)
        start_time = time.time()
        response = session.get(url, timeout=15)
        elapsed = time.time() - start_time
        LOGGER.info("[RicohHTTP] GET %s -> Status %d (%.2fs, length=%d)", target_url, response.status_code, elapsed, len(response.text))
        response.raise_for_status()
        html = response.text

        # If we hit a login page and we are NOT on a guest page, re-authenticate.
        # Also check for "Unable to access authenticated control page" signals
        is_login_page = any(m in html for m in ["authForm.cgi", "login.cgi", "Login User Name"])
        if is_login_page:
            if "/web/guest/" not in url or "Login User Name" in html:
                LOGGER.info("[RicohHTTP] Session expired or auth screen encountered, re-authenticating IP %s...", printer.ip)
                self._login(session, printer)
                LOGGER.info("[RicohHTTP] Re-auth complete. Retrying GET %s...", target_url)
                start_time = time.time()
                response = session.get(url, timeout=15)
                elapsed = time.time() - start_time
                LOGGER.info("[RicohHTTP] Retry GET %s -> Status %d (%.2fs, length=%d)", target_url, response.status_code, elapsed, len(response.text))
                response.raise_for_status()
                html = response.text

        return html

    def _extract_wim_token(self, html: str) -> str:
        # Matches: wimToken="value", wimToken='value', wimToken = value, wimToken: "value", wimToken: 'value'
        match = re.search(r'wimToken\s*[:=]\s*["\']?([^"\'\s;>]+)["\']?', html, re.IGNORECASE)
        if match:
            return match.group(1)
        # Matches: name="wimToken" value="value", name='wimToken' value='value', name=wimToken value=value
        match = re.search(r'name\s*=\s*["\']?wimToken["\']?\s+value\s*=\s*["\']?([^"\'\s>]+)["\']?', html, re.IGNORECASE)
        if match:
            return match.group(1)
        # Matches: value="value" name="wimToken", value='value' name='wimToken', value=value name=wimToken
        match = re.search(r'value\s*=\s*["\']?([^"\'\s>]+)["\']?\s+name\s*=\s*["\']?wimToken["\']?', html, re.IGNORECASE)
        return match.group(1) if match else ""

    def _extract_hidden_inputs(self, html: str) -> dict[str, str]:
        """Simple regex extraction of hidden input fields."""
        fields: dict[str, str] = {}
        for match in re.finditer(
            r'<input\s+[^>]*?type\s*=\s*["\']?hidden["\']?[^>]*?>', html, re.IGNORECASE | re.DOTALL
        ):
            tag = match.group(0)
            name_m = re.search(r'name\s*=\s*["\']?([^"\'\s>]+)["\']?', tag, re.IGNORECASE)
            value_m = re.search(r'value\s*=\s*["\']?([^"\'\s>]*)["\']?', tag, re.IGNORECASE)
            if name_m:
                fields[name_m.group(1)] = unescape(value_m.group(1)) if value_m else ""
        
        # Also check for wimToken variable in script or document
        if "wimToken" not in fields or not fields["wimToken"]:
            token = self._extract_wim_token(html)
            if token:
                fields["wimToken"] = token
        return fields

    @staticmethod
    def _strip_html(input_value: str) -> str:
        text = re.sub(r"<[^>]*>", "", input_value)
        text = re.sub(r"\s+", " ", text)
        return unescape(text.strip())

    @staticmethod
    def _pick_field_key(keys: list[str], candidates: list[str]) -> str | None:
        for c in candidates:
            if c in keys:
                return c
            # Case insensitive check
            for k in keys:
                if k.lower() == c.lower():
                    return k
        return None
