from __future__ import annotations

import logging
import re
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any
from urllib.parse import urljoin

import requests

from app.services.api_client import APIClient, Printer

LOGGER = logging.getLogger(__name__)
ADDRESS_DEBUG_LOG_FILE = Path("storage/data/address_list_debug.log")

@dataclass
class AddressEntry:
    type: str
    registration_no: str
    name: str
    user_code: str
    date_last_used: str
    email_address: str
    folder: str
    entry_id: str = ""

class RicohServiceBase:
    def __init__(self, api_client: APIClient, interval_seconds: int = 60) -> None:
        self.api_client = api_client
        self.interval_seconds = interval_seconds
        self._stop_event = threading.Event()
        self._thread: threading.Thread | None = None
        # Keep a monotonic local hint so address registration_no generated by app always increases.
        self._address_index_hint_by_ip: dict[str, int] = {}

    def _timestamp(self) -> str:
        return time.strftime("%Y-%m-%d %H:%M:%S")

    def _append_address_debug(self, message: str) -> None:
        try:
            ADDRESS_DEBUG_LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
            with ADDRESS_DEBUG_LOG_FILE.open("a", encoding="utf-8") as f:
                f.write(f"{self._timestamp()} {message}\n")
        except Exception as exc:  # noqa: BLE001
            LOGGER.warning("Failed to write address debug log: %s", exc)

    @staticmethod
    def _http_get(url: str, timeout: int = 10, session: requests.Session | None = None) -> str:
        if session:
            resp = session.get(url, timeout=timeout)
        else:
            resp = requests.get(url, timeout=timeout)
        resp.raise_for_status()
        return resp.text

    def _logout_after_collect(self, printer: Printer, source: str = "") -> None:
        logout_url = f"http://{printer.ip}/web/entry/en/websys/webArch/logout.cgi"
        try:
            # We don't bother checking response, typically we just hit it and move on.
            requests.get(logout_url, timeout=5)
            LOGGER.info("Logged out from %s (%s)", printer.name, source)
        except Exception as exc:  # noqa: BLE001
            LOGGER.debug("Logout failed (expected for some models): ip=%s error=%s", printer.ip, exc)

    def _login(self, session: requests.Session, printer: Printer, credential_candidates: list[tuple[str, str]] | None = None) -> tuple[str, str]:
        """
        Unified login logic that tries multiple credential pairs.
        Cycles through candidates: (user, password).
        Returns successfully used (user, password) tuple.
        """
        base_url = f"http://{printer.ip}"
        
        # 1. First, always reset/logout to ensure we aren't in a broken state.
        self._reset_web_session(session, printer)
        
        # 2. Build candidate list.
        # Priority: explicit candidates -> printer's own -> common defaults.
        candidates = []
        if credential_candidates:
            candidates.extend(credential_candidates)
        
        if printer.user or printer.password:
            candidates.append((printer.user or "", printer.password or ""))
        
        candidates.extend([
            ("admin", ""),
            ("admin", "admin"),
        ])
        
        # Deduplicate candidates while preserving order.
        seen = set()
        final_candidates = []
        for u, p in candidates:
            if (u, p) not in seen:
                seen.add((u, p))
                final_candidates.append((u, p))

        last_exception = None
        for attempt, (user, password) in enumerate(final_candidates):
            try:
                # Some models need login.cgi, others authForm.cgi
                login_urls = [
                    "/web/entry/en/websys/webArch/authForm.cgi",
                    "/web/entry/en/websys/webArch/login.cgi"
                ]
                
                success = False
                for login_path in login_urls:
                    try:
                        resp = session.post(
                            urljoin(base_url, login_path),
                            data={
                                "username": user,
                                "password": password,
                                "wimToken": "" # Usually empty on first hit
                            },
                            timeout=10
                        )
                        if resp.status_code == 200 and ("login.cgi" not in resp.text and "authForm.cgi" not in resp.text):
                            success = True
                            break
                    except Exception:
                        continue
                
                if success:
                    # Persist winner
                    printer.user = user
                    printer.password = password
                    LOGGER.info("Login success: ip=%s user=%s", printer.ip, user)
                    return (user, password)
                
            except Exception as exc:
                last_exception = exc
                if attempt < len(final_candidates) - 1:
                    time.sleep(1)
                    continue

        if last_exception:
            raise last_exception
        raise RuntimeError(f"All login attempts failed for {printer.ip}")

    def _login_auth_form_only(self, session: requests.Session, printer: Printer) -> None:
        """Deprecated/Legacy: Use unified _login instead if possible."""
        self._login(session, printer)

    def _reset_web_session(self, session: requests.Session, printer: Printer) -> None:
        base_url = f"http://{printer.ip}"
        # Best-effort logout/cleanup
        urls = [
            "/web/entry/en/websys/webArch/logout.cgi",
            "/web/guest/en/websys/webArch/logout.cgi",
            "/web/entry/en/websys/webArch/mainFrame.cgi",
            "/web/guest/en/websys/webArch/mainFrame.cgi",
        ]
        for target in urls:
            try:
                session.get(urljoin(base_url, target), timeout=8)
            except Exception:  # noqa: BLE001
                continue
        try:
            session.cookies.clear()
        except Exception:  # noqa: BLE001
            return

    def create_http_client(self, printer: Printer, credential_candidates: list[tuple[str, str]] | None = None, authenticated: bool = True) -> requests.Session:
        """
        Creates a session. If authenticated=True, performs login.
        """
        session = requests.Session()
        session.headers.update({"User-Agent": "printer-agent/0.1"})
        
        if authenticated:
            self._login(session, printer, credential_candidates=credential_candidates)
        return session

    def create_http_client_auth_form_only(self, printer: Printer) -> requests.Session:
        """Deprecated: Use create_http_client instead."""
        return self.create_http_client(printer, authenticated=True)

    def authenticate_and_get(self, session: requests.Session, printer: Printer, target_url: str) -> str:
        """
        Compatibility layer: Ensures we are logged in and fetches the target.
        """
        url = urljoin(f"http://{printer.ip}", target_url)
        response = session.get(url, timeout=10)
        response.raise_for_status()
        html = response.text

        # If we hit a login page and we are NOT on a guest page, re-authenticate.
        if "authForm.cgi" in html or "login.cgi" in html or "Login User Name" in html:
            if "/web/guest/" not in url:
                self._login(session, printer)
                response = session.get(url, timeout=10)
                response.raise_for_status()
                html = response.text

        return html

    def _extract_wim_token(self, html: str) -> str:
        match = re.search(r'wimToken\s*=\s*"([^"]+)"', html)
        if match:
            return match.group(1)
        match = re.search(r'name="wimToken"\s*value="([^"]+)"', html)
        return match.group(1) if match else ""

    def _extract_hidden_inputs(self, html: str) -> dict[str, str]:
        """Simple regex extraction of hidden input fields."""
        fields: dict[str, str] = {}
        for match in re.finditer(
            r'<input\s+[^>]*?type=["\']hidden["\'][^>]*?>', html, re.IGNORECASE | re.DOTALL
        ):
            tag = match.group(0)
            name_m = re.search(r'name=["\']([^"\']+)["\']', tag, re.IGNORECASE)
            value_m = re.search(r'value=["\']([^"\']*)["\']', tag, re.IGNORECASE)
            if name_m:
                fields[name_m.group(1)] = unescape(value_m.group(1)) if value_m else ""
        # Also check for wimToken variable in script
        if "wimToken" not in fields:
            token = self._extract_wim_token(html)
            if token:
                fields["wimToken"] = token
        return fields

    @staticmethod
    def _strip_html(input_value: str) -> str:
        text = re.sub(r"<[^>]*>", "", input_value)
        text = re.sub(r"\s+", " ", text)
        return unescape(text.strip())

    @staticmethod
    def _pick_field_key(keys: list[str], candidates: list[str]) -> str | None:
        for c in candidates:
            if c in keys:
                return c
            # Case insensitive check
            for k in keys:
                if k.lower() == c.lower():
                    return k
        return None
